### ISSUE TITLE
DOCKER BUILD fails

### ISSUE THREAD

**Issue by r-cemper** [theanor/ks-iris-lib#1]
failed to solve: intersystemsdc/irishealth-community:2024.2: failed to resolve source metadata for docker.io/intersystemsdc/irishealth-community:2024.2: docker.io/intersystemsdc/irishealth-community:2024.2: not found

**Comment by r-cemper** [comment]
no problens to execute in LATEST

**Comment by theanor** [comment]
now using latest (tagged by code quality gate as intentionality error)

**Comment by theanor** [comment]
now using latest (tagged by code quality gate as intentionality error)
