### ISSUE TITLE
IRIS SCRIPT is never executes

### ISSUE THREAD

**Issue by r-cemper** [theanor/ks-iris-lib#4]
no code is loaded into the image
manually running iris.script works

**Comment by theanor** [comment]
which version of docker are you using ?
does it support this syntax :

**Comment by theanor** [comment]
Hi Robert,

Thank you for your time and expertise.

Which version of docker are you using ?
Does it support the following syntax  ?

`RUN <<EOF
iris start IRIS
iris session IRIS < iris.script
iris stop IRIS quietly
EOF`

**Comment by theanor** [comment]
oops, closed by error

**Comment by r-cemper** [comment]
Windows Docker Dessktop  4.34.2 (167172)
it doesn't accept your way
BUT
# Dockerfile just for Online Demo
# Explicit version for Quality check !!! What a nonsense !!!
ARG IMAGE=intersystemsdc/iris-community
# ARG VERSION=2024.1   
ARG VERSION=latest
FROM $IMAGE:$VERSION
USER root
WORKDIR /home/irisowner/dev  
RUN chown ${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} /home/irisowner/dev
USER ${ISC_PACKAGE_MGRUSER}

COPY src src
COPY module.xml module.xml
COPY iris.script iris.script

RUN iris start IRIS && iris session IRIS < iris.script  && iris stop IRIS quietly

**Comment by theanor** [comment]
I'm using the same docker desktop version. But I think this may be due to container build being finicky about end-of-line characters.

In my git config, I have :

`core.autocrlf=false`

which basically tells git client to stop converting to/from Windows/Un*x eols ($0D vs $0D $0A)

**Comment by r-cemper** [comment]
I found the problem:
- in Dockerfile I see **WORKDIR /opt/irisbuild**
-iris script gets executed BUT: in iris.script there is 
    zpm "load /irisrun/repo -v":1:1
changed it to 
  **zpm "load /opt/irisbuild-v":1**

now all modules are loaded and compiled
I usually run zpm "list" as final command in iris.script to verify my zpm installs

**Comment by r-cemper** [comment]
I changed the Dcockerfile to **RUN <<EO**F format and it worked.
It was just the wrong directory that prevented any traces. In combination with the :1:1  after load:
the second :1  kills the process immediately

**Comment by theanor** [comment]
Thank you Robert, it is  indeed building correctly now
